
service: sls-strapi
frameworkVersion: "4"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  profile: serverless-strapi-admin
  logRetentionInDays: 1
  versionFunctions: false

  memorySize: 2048
  timeout: 30

  environment:
    APP_KEYS: ${env:APP_KEYS}
    API_TOKEN_SALT: ${env:API_TOKEN_SALT}
    ADMIN_JWT_SECRET: ${env:ADMIN_JWT_SECRET}
    JWT_SECRET: ${env:JWT_SECRET}

    SERVER_URL: ${env:SERVER_URL}
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
    DATABASE_USERNAME: ${env:DATABASE_USERNAME}
    DATABASE_NAME: ${env:DATABASE_NAME}
    DATABASE_HOST: ${env:DATABASE_HOST}
package:
  excludeDevDependencies: false
  patterns:
    - "build/**"
    - "config/**"
    - "database/**"
    - "public/**"
    - "src/**"
    - ".env.example"
    - "package.json"
    - "types/**"
    - "node_modules/sharp/**"
    - "node_modules/**/sharp/**"
    - "!node_modules/**"
    - "!node_modules/**/README.*"
    - "!node_modules/**/test/**"
    - "!node_modules/@floating-ui/**"
    - "!node_modules/@react-dnd/**"
    - "!node_modules/@sentry/**"
    - "!node_modules/css-color-keywords/**"
    - "!node_modules/css-loader/**"
    - "!node_modules/css-to-react-native/**"
    - "!node_modules/css-what/**"
    - "!node_modules/prettier-plugin-packagejson/**"
    - "!node_modules/redux*/**"
    - "!node_modules/react*/**"
    - "!node_modules/styled-components/**"
    - "!node_modules/webpack*/**"
functions:
  api:
    handler: src/app.strapiHandler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{any+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

custom:
  serverless-offline:
    httpPort: 4000